name: macOS gtk4

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'gtk4 pango glib glib-networking gobject-introspection pkg-config jq' }}

on:
  push:
    branches:
      - gtk4
  pull_request:
    branches:
      - gtk4

jobs:
  # macOS tasks
  build-mac-gtk4-swift-latest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.3'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Run brew update
        run: brew update

      - name: Upgrade installed packages to current version
        run: brew upgrade
        continue-on-error: true

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW
        if: ${{ success() || failure() }}

      - name: Checkout SwiftHelloGtkBuilder
        uses: actions/checkout@v2
        with:
          path: SwiftHelloGtkBuilder

      - name: Build Swift Wrappers
        run: |
          cd SwiftHelloGtkBuilder
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftHelloGtkBuilder
        run: |
          cd SwiftHelloGtkBuilder
          swift build -Xswiftc -suppress-warnings `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Create SwiftHelloGtkBuilder App Bundle
        run: |
          cd SwiftHelloGtkBuilder
          ./app-bundle.sh
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd SwiftHelloGtkBuilder
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact-macos-gtk4
          path: |
            SwiftHelloGtkBuilder/
          retention-days: 1
